'use strict';

const fs   = require('fs');
const path = require('path');

const { PATHS }                   = require('./paths');
const { fileExists, readJsonSafe, readFileNormalized } = require('./file-utils');
const { toggleModule }            = require('./modules');

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const CUSTOM_DIR    = path.join(PATHS.modulesDir, 'custom-launcher');
const ITEMS_JSON    = path.join(CUSTOM_DIR, 'items.json');
const MODULE_TS     = path.join(CUSTOM_DIR, 'module.ts');
const EXPORT_NAME   = 'customLauncherModule';
const MODULE_ID     = 'custom-launcher';
const TAB_PREFIX    = 'cl-';

const MANIFEST_META = [
  "  author: 'Two Birds Code',",
  "  authorUrl: 'https://twobirdscode.com',",
  "  license: 'Proprietary',",
];

// ---------------------------------------------------------------------------
// Read items
// ---------------------------------------------------------------------------

function readLauncherItems() {
  const data = readJsonSafe(ITEMS_JSON);
  return (data && Array.isArray(data.items)) ? data.items : [];
}


// ---------------------------------------------------------------------------
// Write items + regenerate module
// ---------------------------------------------------------------------------

function writeLauncherItems(items) {
  fs.mkdirSync(CUSTOM_DIR, { recursive: true });
  fs.writeFileSync(ITEMS_JSON, JSON.stringify({ items }, null, 2) + '\n');
  fs.writeFileSync(MODULE_TS, generateModuleTs(items));
  syncTabRouteStubs(items);

  if (items.length > 0) {
    toggleModule(MODULE_ID, true);
    const tabItems = items.filter(i => i.showInTabBar === true);
    ensureMultiTabRegistry(tabItems);
  } else {
    // No items left — fully clean up the generated module
    toggleModule(MODULE_ID, false);
    fs.rmSync(CUSTOM_DIR, { recursive: true, force: true });
  }

  return { ok: true };
}

// ---------------------------------------------------------------------------
// Code generation — shared helpers
// ---------------------------------------------------------------------------

function appendLauncherItems(lines, launcherItems) {
  lines.push('');
  lines.push('  launcherItems: [');
  for (let i = 0; i < launcherItems.length; i++) {
    const item = launcherItems[i];
    lines.push('    {');
    lines.push(`      id: '${escapeTs(item.id)}',`);
    lines.push(`      label: '${escapeTs(item.label)}',`);
    lines.push(`      icon: '${escapeTs(item.icon)}',`);
    lines.push(`      route: ${formatRoute(item)},`);
    lines.push(`      order: ${(i + 1) * 10},`);
    if (item.hideKey) lines.push(`      hideKey: '${escapeTs(item.hideKey)}',`);
    if (item.iconColor) lines.push(`      iconColor: '${escapeTs(item.iconColor)}',`);
    if (item.iconBackground) lines.push(`      iconBackground: '${escapeTs(item.iconBackground)}',`);
    lines.push('    },');
  }
  lines.push('  ],');
}

function appendTabBlock(lines, tab) {
  const tabName = TAB_PREFIX + sanitizeId(tab.id);
  const iconBase = tab.icon.replace('-outline', '').replace('-sharp', '');
  lines.push('');
  lines.push('  tab: {');
  lines.push(`    name: '${tabName}',`);
  lines.push(`    title: '${escapeTs(tab.label)}',`);
  lines.push(`    icon: '${escapeTs(iconBase)}',`);
  lines.push(`    iconOutline: '${escapeTs(tab.icon.includes('-outline') ? tab.icon : iconBase + '-outline')}',`);
  lines.push('    order: 90,');
  lines.push('    component: () => null,');
  if (tab.hideKey) lines.push(`    hideMenuKey: '${escapeTs(tab.hideKey)}',`);
  if (tab.iconColor) lines.push(`    tabColor: '${escapeTs(tab.iconColor)}',`);
  lines.push('    interceptPress: (router) => {');
  lines.push(`      router.push(${formatRoute(tab)});`);
  lines.push('    },');
  lines.push('  },');
}

function appendManifestHeader(lines, exportName, id, name, description) {
  lines.push(`export const ${exportName}: ModuleManifest = {`);
  lines.push(`  id: '${id}',`);
  lines.push(`  name: '${escapeTs(name)}',`);
  lines.push("  version: '1.0.0',");
  lines.push(`  description: '${escapeTs(description)}',`);
  lines.push(...MANIFEST_META);
}

// ---------------------------------------------------------------------------
// Generate module.ts from items
// ---------------------------------------------------------------------------

function generateModuleTs(items) {
  const activeItems = items.filter(i => i.enabled !== false);
  const launcherItems = activeItems.filter(i => i.showInLauncher !== false);
  const tabItems = activeItems.filter(i => i.showInTabBar === true);

  const lines = [];
  lines.push('// GENERATED BY DASHBOARD — DO NOT EDIT');
  lines.push('// Source: modules/custom-launcher/items.json');
  lines.push("import type { ModuleManifest } from '../_types';");
  lines.push('');

  // Multiple tabs require separate manifests (ModuleManifest only supports one tab)
  if (tabItems.length > 1) {
    return generateMultiTabModule(lines, launcherItems, tabItems);
  }

  appendManifestHeader(lines, EXPORT_NAME, MODULE_ID, 'Custom Launcher', 'Buyer-defined launcher and tab bar items');
  if (launcherItems.length > 0) appendLauncherItems(lines, launcherItems);
  if (tabItems.length === 1) appendTabBlock(lines, tabItems[0]);
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

function generateMultiTabModule(lines, launcherItems, tabItems) {
  // Primary manifest: all launcher items + first tab
  appendManifestHeader(lines, EXPORT_NAME, MODULE_ID, 'Custom Launcher', 'Buyer-defined launcher and tab bar items');
  if (launcherItems.length > 0) appendLauncherItems(lines, launcherItems);
  appendTabBlock(lines, tabItems[0]);
  lines.push('};');
  lines.push('');

  // Additional tab manifests
  for (let t = 1; t < tabItems.length; t++) {
    const tab = tabItems[t];
    const exportN = `${EXPORT_NAME}Tab${t + 1}`;
    appendManifestHeader(lines, exportN, `${MODULE_ID}-tab-${t + 1}`, `Custom Tab: ${tab.label}`, 'Buyer-defined tab bar item');
    appendTabBlock(lines, tab);
    lines.push('};');
    lines.push('');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Route formatting
// ---------------------------------------------------------------------------

function formatRoute(item) {
  if (item.linkType === 'internal') {
    return `'${escapeTs(item.url)}'`;
  }
  if (item.linkType === 'external' && item.openInBrowser) {
    return `{ pathname: '/open-link', params: ${JSON.stringify({ url: item.url })} }`;
  }
  const params = { url: item.url, title: item.label };
  if (item.linkType === 'external') {
    params.noAuth = 'true';
  }
  return `{ pathname: '/webview', params: ${JSON.stringify(params)} }`;
}

// ---------------------------------------------------------------------------
// Tab route stub management
// ---------------------------------------------------------------------------

function syncTabRouteStubs(items) {
  const tabItems = items.filter(i => i.showInTabBar === true);
  const wantedStubs = new Set(tabItems.map(i => TAB_PREFIX + sanitizeId(i.id) + '.tsx'));

  for (const tab of tabItems) {
    const stubName = TAB_PREFIX + sanitizeId(tab.id) + '.tsx';
    const stubPath = path.join(PATHS.tabsDir, stubName);
    if (!fileExists(stubPath)) {
      const funcName = 'Cl' + capitalize(sanitizeId(tab.id)) + 'Screen';
      const content = [
        '// GENERATED BY DASHBOARD — DO NOT EDIT',
        "import { View } from 'react-native';",
        '',
        `export default function ${funcName}() { return <View />; }`,
        '',
      ].join('\n');
      fs.writeFileSync(stubPath, content);
    }
  }

  if (fileExists(PATHS.tabsDir)) {
    const existing = fs.readdirSync(PATHS.tabsDir).filter(f => f.startsWith(TAB_PREFIX) && f.endsWith('.tsx'));
    for (const file of existing) {
      if (!wantedStubs.has(file)) {
        fs.unlinkSync(path.join(PATHS.tabsDir, file));
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Registry patching for multi-tab
// ---------------------------------------------------------------------------
// toggleModule only registers the primary export. When >1 tab items exist,
// extra exports (customLauncherModuleTab2, etc.) need to be added too.

function ensureMultiTabRegistry(tabItems) {
  if (tabItems.length <= 1) return;
  if (!fileExists(PATHS.registryTs)) return;

  let content = readFileNormalized(PATHS.registryTs);

  for (let t = 1; t < tabItems.length; t++) {
    const exportN = `${EXPORT_NAME}Tab${t + 1}`;
    if (content.includes(exportN)) continue;

    content = content.replace(
      new RegExp(`import \\{ ${EXPORT_NAME}([^}]*) \\} from '\\./${MODULE_ID}/module'`),
      `import { ${EXPORT_NAME}$1, ${exportN} } from './${MODULE_ID}/module'`
    );
    content = content.replace(
      /(export const MODULES: ModuleManifest\[\] = \[)([\s\S]*?)(\n\];)/,
      (_m, open, body, close) => `${open}${body}\n  ${exportN},${close}`
    );
  }

  // Clean stale tab exports that no longer exist
  const activeExports = new Set([EXPORT_NAME]);
  for (let t = 1; t < tabItems.length; t++) {
    activeExports.add(`${EXPORT_NAME}Tab${t + 1}`);
  }
  const stalePattern = /customLauncherModuleTab(\d+)/g;
  let match;
  const staleExports = new Set();
  while ((match = stalePattern.exec(content)) !== null) {
    if (!activeExports.has(match[0])) staleExports.add(match[0]);
  }
  for (const stale of staleExports) {
    content = content.replace(new RegExp(`,\\s*${stale}`, 'g'), '');
    content = content.replace(new RegExp(`${stale},\\s*`, 'g'), '');
    content = content.replace(new RegExp(`\\s*${stale},?\\n`, 'g'), '\n');
  }

  content = content.replace(/\n{3,}/g, '\n\n');
  fs.writeFileSync(PATHS.registryTs, content);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function escapeTs(str) {
  return String(str || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function sanitizeId(str) {
  return String(str || '').replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// ---------------------------------------------------------------------------
// Available App Routes (for internal route dropdown)
// ---------------------------------------------------------------------------

function getAvailableRoutes() {
  if (!fileExists(PATHS.appDir)) return [];

  const skip = new Set(['_layout.tsx', '(tabs)', 'login.tsx', 'register.tsx', 'forgot-password.tsx', 'open-link.tsx', 'webview.tsx', 'profile-complete.tsx']);
  const routes = [];
  const entries = fs.readdirSync(PATHS.appDir, { withFileTypes: true });

  for (const entry of entries) {
    if (skip.has(entry.name) || entry.name.startsWith('_') || entry.name.startsWith('.')) continue;

    if (entry.isDirectory()) {
      routes.push({ path: '/' + entry.name, label: capitalize(entry.name.replace(/-/g, ' ')) });
    } else if (entry.name.endsWith('.tsx') && !entry.name.startsWith('[')) {
      const name = entry.name.replace('.tsx', '');
      routes.push({ path: '/' + name, label: capitalize(name.replace(/-/g, ' ')) });
    }
  }

  return routes.sort((a, b) => a.label.localeCompare(b.label));
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

module.exports = {
  readLauncherItems,
  writeLauncherItems,
  getAvailableRoutes,
};
