<?php

// Auto generated by wpfluent Installer.

return array(
    'name'         => 'FluentCommunity Chat',
    'slug'         => 'fluent-messaging',
    'domain_path'  => '/language',
    'text_domain'  => 'fluent-messaging',
    'hook_prefix'  => 'fluent-messaging',
    'rest_version' => 'v2',
    'env'          => 'dev',
);
