// GENERATED BY DASHBOARD — DO NOT EDIT
// Source: modules/custom-launcher/items.json
import type { ModuleManifest } from '../_types';

export const customLauncherModule: ModuleManifest = {
  id: 'custom-launcher',
  name: 'Custom Launcher',
  version: '1.0.0',
  description: 'Buyer-defined launcher and tab bar items',
  author: 'Two Birds Code',
  authorUrl: 'https://twobirdscode.com',
  license: 'Proprietary',

  launcherItems: [
    {
      id: 'admin',
      label: 'Admin',
      icon: 'shield-outline',
      route: { pathname: '/webview', params: {"url":"https://community.twobirdschurch.com/tbc-admin/","title":"Admin"} },
      order: 10,
      hideKey: 'admin',
      iconColor: 'warning',
      iconBackground: 'warning',
    },
  ],
};
