// GENERATED BY DASHBOARD — DO NOT EDIT
// Source: modules/custom-launcher/items.json
import type { ModuleManifest } from '../_types';

export const customLauncherModule: ModuleManifest = {
  id: 'custom-launcher',
  name: 'Custom Launcher',
  version: '1.0.0',
  description: 'Buyer-defined launcher and tab bar items',
  author: 'Two Birds Code',
  authorUrl: 'https://twobirdscode.com',
  license: 'Proprietary',

  launcherItems: [
    {
      id: 'admin',
      label: 'Admin',
      icon: 'shield-outline',
      route: { pathname: '/webview', params: {"url":"https://community.twobirdschurch.com/tbc-admin/","title":"Admin"} },
      order: 10,
      hideKey: 'admin',
      iconColor: 'warning',
      iconBackground: 'warning',
    },
    {
      id: 'donate',
      label: 'Donate',
      icon: 'heart-outline',
      route: { pathname: '/webview', params: {"url":"https://community.twobirdschurch.com/calendar/donate/","title":"Donate"} },
      order: 20,
      hideKey: 'donate',
      iconColor: 'error',
      iconBackground: 'error',
    },
    {
      id: 'donor-dashboard',
      label: 'Donor Dashboard',
      icon: 'wallet-outline',
      route: { pathname: '/webview', params: {"url":"https://community.twobirdschurch.com/donor-dashboard/","title":"Donor Dashboard"} },
      order: 30,
      hideKey: 'donor_dashboard',
    },
  ],

  tab: {
    name: 'cl-donate',
    title: 'Donate',
    icon: 'heart',
    iconOutline: 'heart-outline',
    order: 90,
    component: () => null,
    hideMenuKey: 'donate',
    tabColor: 'error',
    interceptPress: (router) => {
      router.push({ pathname: '/webview', params: {"url":"https://community.twobirdschurch.com/calendar/donate/","title":"Donate"} });
    },
  },
};
